[package]
name = "protolab-schema"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
panproto-schema.workspace = true
panproto-gat.workspace = true
panproto-protocols.workspace = true
panproto-lens.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
